import { NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// 1. GET: ดึงแผนกทั้งหมด
export async function GET() {
  try {
    const departments = await prisma.department.findMany({
      orderBy: { departmentCode: 'asc' }
    });
    return NextResponse.json(departments);
  } catch (error) {
    return NextResponse.json({ error: 'ไม่สามารถดึงข้อมูลแผนกได้' }, { status: 500 });
  }
}

// 2. POST: เพิ่มแผนกใหม่ (🌟 รันรหัสอัตโนมัติ)
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { departmentName } = body;

    if (!departmentName) {
      return NextResponse.json({ error: 'กรุณากรอกชื่อแผนก' }, { status: 400 });
    }

    // 🌟 ดึงรหัสแผนกเดิมทั้งหมดมาเพื่อหาตัวเลขสูงสุด
    const allDepts = await prisma.department.findMany();
    const dptNumbers = allDepts
      .filter(d => d.departmentCode.startsWith('DPT-'))
      .map(d => parseInt(d.departmentCode.replace('DPT-', ''), 10))
      .filter(n => !isNaN(n));
      
    const maxNumber = dptNumbers.length > 0 ? Math.max(...dptNumbers) : 0;
    const autoGeneratedCode = `DPT-${String(maxNumber + 1).padStart(3, '0')}`; // ผลลัพธ์: DPT-001, DPT-002...

    const newDept = await prisma.department.create({
      data: { 
        departmentCode: autoGeneratedCode, 
        departmentName 
      }
    });

    return NextResponse.json({ success: true, data: newDept }, { status: 201 });
  } catch (error: any) {
    return NextResponse.json({ error: 'เกิดข้อผิดพลาดในการบันทึกข้อมูล' }, { status: 500 });
  }
}

// 3. PUT: แก้ไขแผนก
export async function PUT(request: Request) {
  try {
    const body = await request.json();
    const { departmentCode, departmentName } = body;

    const updatedDept = await prisma.department.update({
      where: { departmentCode },
      data: { departmentName }
    });

    return NextResponse.json({ success: true, data: updatedDept });
  } catch (error) {
    return NextResponse.json({ error: 'ไม่สามารถแก้ไขข้อมูลได้' }, { status: 500 });
  }
}

// 4. DELETE: ลบแผนก
export async function DELETE(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const departmentCode = searchParams.get('id');

    if (!departmentCode) {
      return NextResponse.json({ error: 'ไม่พบรหัสแผนก' }, { status: 400 });
    }

    await prisma.department.delete({
      where: { departmentCode }
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    return NextResponse.json({ error: 'ไม่สามารถลบแผนกได้ เนื่องจากอาจมีพนักงานผูกอยู่กับแผนกนี้' }, { status: 500 });
  }
}